# Add seed data here. Seed your database with `rake db:seed`
Runner.create(name: "Kathrine Switzer", gender: "female", password: "testpass", email: "kathrine.switzer@gmail.com")
Runner.create(name: "Florence Griffith-Joyner", gender: "female", password: "testpass", email: "florence.griffith-joyner@gmail.com")
Runner.create(name: "Paula Radcliffe", gender: "female", password: "testpass", email: "paula.radcliffe@gmail.com")
Runner.create(name: "Allyson Felix", gender: "female", password: "testpass", email: "allyson.felix@gmail.com")
Runner.create(name: "Wyomia Tyus", gender: "female", password: "testpass", email: "wyomia.tyus@gmail.com")
Runner.create(name: "Wilma Rudolph", gender: "female", password: "testpass", email: "wilma.rudolph@gmail.com")
Runner.create(name: "Gail Devers", gender: "female", password: "testpass", email: "gail.devers@gmail.com")
Runner.create(name: "Mary Decker Slaney", gender: "female", password: "testpass", email: "mary.decker.slaney@gmail.com")
Runner.create(name: "Evelyn Ashford", gender: "female", password: "testpass", email: "evelyn.ashford@gmail.com")
Runner.create(name: "Joan Benoit", gender: "female", password: "testpass", email: "joan.benoit@gmail.com")
Runner.create(name: "Jesse Owens", gender: "male", password: "testpass", email: "jesse.owens@gmail.com")
Runner.create(name: "Roger Bannister", gender: "male", password: "testpass", email: "roger.bannister@gmail.com")
Runner.create(name: "Abebe Bikila", gender: "male", password: "testpass", email: "abebe.bikila@gmail.com")
Runner.create(name: "Lee Evans", gender: "male", password: "testpass", email: "lee.evans@gmail.com")
Runner.create(name: "Steve Prefontaine", gender: "male", password: "testpass", email: "steve.prefontaine@gmail.com")
Runner.create(name: "Sebastian Coe", gender: "male", password: "testpass", email: "sebastian.coe@gmail.com")
Runner.create(name: "Linford Christie", gender: "male", password: "testpass", email: "linford.christie@gmail.com")
Runner.create(name: "Dean Karnazes", gender: "male", password: "testpass", email: "dean.karnazes@gmail.com")
Runner.create(name: "Mo Farah", gender: "male", password: "testpass", email: "mo.farah@gmail.com")
Runner.create(name: "Usain Bolt", gender: "male", password: "testpass", email: "usain.bolt@gmail.com")
Workout.create(distance: 11.35, workout_date: "2017-03-12", runner_id: 1, notes: "One late afternoon, after swimming in a lake, he began to jog around to ease his chill.       Soon enough he found himself running for the sheer exhilaration of it, across the moor and toward the coast.  The sky filled with crimson clouds, and as he ran a light rain started to fall.  With the sun warming his back, a rainbow appeared in front of him, and he seemed to run toward it. Along the coast the rhythm of the water breaking against the rocks eased him, and he circled back to where he had begun.  Cool, wet air filled his lungs.  Running into the sun now, he had trouble seeing the ground underneath his feet, but still he rushed forward, alive with the movement.  Finally spent as the sun disappeared from the horizon, he tumbled down a light hill and rested on his back, his feet bleeding, but feeling rejuvenated. He needed to reconnect to the joy of running, to get away from the tyranny of the track")
Workout.create(distance: 18.53, workout_date: "2017-03-20", runner_id: 12, notes: "For me, like so many others, running is the answer. Out on the road it is just you, the pavement, and your will.")
Workout.create(distance: 7.52, workout_date: "2017-03-04", runner_id: 12, notes: "In running it is man against himself, the cruelest of opponents. The other runners are not the real enemies. His adversary lies within him, in his ability with brain and heart to master himself and his emotions.")
Workout.create(distance: 11.55, workout_date: "2017-03-02", runner_id: 11, notes: "'Come to the edge,' he said.")
Workout.create(distance: 1.16, workout_date: "2017-03-13", runner_id: 19, notes: "They said, 'But we're afraid.'")
Workout.create(distance: 7.8, workout_date: "2017-03-28", runner_id: 20, notes: "'Come to the edge,' he said.")
Workout.create(distance: 3.65, workout_date: "2017-03-14", runner_id: 18, notes: "They came.")
Workout.create(distance: 10.19, workout_date: "2017-03-09", runner_id: 13, notes: "He pushed them,")
Workout.create(distance: 17.23, workout_date: "2017-03-11", runner_id: 15, notes: "and they flew.")
Workout.create(distance: 5.38, workout_date: "2017-03-22", runner_id: 20, notes: "1. Stress improvement, not perfection (or winning). 2. Don't take yourself too seriously; laugh at yourself and have fun. 3. Set attainable goals; reach them and then set higher ones. 4. Be positive, walk tall, smile often, don't complain or procrastinate. 5. Prepare purposely, but don't overtrain. 6. Remember- Sports is a game and meant to be enjoyable.")
Workout.create(distance: 4.75, workout_date: "2017-03-19", runner_id: 7, notes: "A coach can be like oasis in the desert of a runner's lost enthusiasm.")
Workout.create(distance: 6.96, workout_date: "2017-03-03", runner_id: 10, notes: "A man can fail many times, but he isn't a failure until he begins to blame somebody else.")
Workout.create(distance: 9.53, workout_date: "2017-03-03", runner_id: 6, notes: "A marathon is like life with its ups and downs, but once you've done it, you feel you can do anything.")
Workout.create(distance: 10.91, workout_date: "2017-03-01", runner_id: 14, notes: "A race is a work of art that people can look at and be affected by in as many ways as they're capable of understanding. ")
Workout.create(distance: 15.92, workout_date: "2017-03-06", runner_id: 6, notes: "A runner must run with dreams in his heart.")
Workout.create(distance: 5.05, workout_date: "2017-03-03", runner_id: 20, notes: "A star can win any game; a team can win every game")
Workout.create(distance: 19.13, workout_date: "2017-03-14", runner_id: 3, notes: "A woman shouldn't have to be hit by a car to learn that she might have rabies.  But that is where we are in America and that does not sit right with me.  And that's why I am hosting a fun race for the cure for rabies.  To raise awareness of that fact that there is a cure for rabies.  A disease that has largely been eradicated in the United States but not many people know that.")
Workout.create(distance: 2.91, workout_date: "2017-03-10", runner_id: 4, notes: "Ability is what you are capable of doing. Motivation determines what you do. Attitude is how well you do it.")
Workout.create(distance: 9.53, workout_date: "2017-03-24", runner_id: 15, notes: "Act like a horse. Be dumb. Just run.")
Workout.create(distance: 16.76, workout_date: "2017-03-05", runner_id: 8, notes: "Any idiot can train himself into the ground; the trick is working in training to get gradually stronger.")
Workout.create(distance: 18.02, workout_date: "2017-03-13", runner_id: 13, notes: "Anything is possible, but you have to believe and you have to fight.")
Workout.create(distance: 12.9, workout_date: "2017-03-09", runner_id: 17, notes: "As athletes, we have ups and downs. Unfortunately, you can't pick the days they come on.")
Workout.create(distance: 13.88, workout_date: "2017-03-17", runner_id: 20, notes: "Besides pride, loyalty, discipline, heart, and mind, confidence is the key to all the locks.")
Workout.create(distance: 19.23, workout_date: "2017-03-18", runner_id: 8, notes: "Bid me run and I will strive with things impossible.")
Workout.create(distance: 17.77, workout_date: "2017-03-12", runner_id: 3, notes: "Citius, altius, fortius...swifter, higher, stronger. ")
Workout.create(distance: 9.23, workout_date: "2017-03-16", runner_id: 2, notes: "Coming off the last turn, my thoughts changed from 'One more try...one more try...one more try...' to 'I can win! I can win! I can win!")
Workout.create(distance: 14.99, workout_date: "2017-03-13", runner_id: 13, notes: "Desire is the most important factor in the success of any athlete.")
Workout.create(distance: 9.46, workout_date: "2017-03-25", runner_id: 8, notes: "Do no go where the path may lead, go instead where there is no path and leave a trail.")
Workout.create(distance: 11.92, workout_date: "2017-03-02", runner_id: 14, notes: "Do not let what you cannot do interfere with what you can do.")
Workout.create(distance: 9.45, workout_date: "2017-03-27", runner_id: 12, notes: "Don't attack a hill from the very bottom- it's bigger than you are!")
Workout.create(distance: 2.79, workout_date: "2017-03-16", runner_id: 18, notes: "Don't be pushed by your problems. Be led by your dreams.")
Workout.create(distance: 13.19, workout_date: "2017-03-29", runner_id: 2, notes: "Don't bother just to be better than your contemporaries or predecessors. Try to be better than yourself. ")
Workout.create(distance: 4.65, workout_date: "2017-03-07", runner_id: 8, notes: "Don't give up on the impossible before you try it.")
Workout.create(distance: 12.85, workout_date: "2017-03-04", runner_id: 16, notes: "Dream the impossible, do the incredible.")
Workout.create(distance: 10.09, workout_date: "2017-03-18", runner_id: 4, notes: "Even if you fall flat on your face at least you are moving forward")
Workout.create(distance: 16.31, workout_date: "2017-03-10", runner_id: 6, notes: "Every morning in Africa, a gazelle wakes up. It knows it must run faster than the fastest lion or it will be killed. Every morning a lion wakes up. It knows it must outrun the slowest gazelle or it will starve to death. It doesn't matter whether you are a lion or a gazelle; when the sun comes up, you'd better be running.")
Workout.create(distance: 6.81, workout_date: "2017-03-27", runner_id: 12, notes: "Every time I fail I assume I will be a stronger person for it. ")
Workout.create(distance: 14.18, workout_date: "2017-03-20", runner_id: 6, notes: "Everything I know about life, I learned it from running.")
Workout.create(distance: 4.95, workout_date: "2017-03-14", runner_id: 12, notes: "Exercise is done against one's wishes and maintained only because the alternative is worse. ")
Workout.create(distance: 10.17, workout_date: "2017-03-16", runner_id: 2, notes: "Failing to prepare is preparing to fail.")
Workout.create(distance: 18.93, workout_date: "2017-03-25", runner_id: 2, notes: "Faith is believing. Believing is winning.")
Workout.create(distance: 3.67, workout_date: "2017-03-04", runner_id: 18, notes: "Feel the fear and do it anyway.")
Workout.create(distance: 2.22, workout_date: "2017-03-20", runner_id: 2, notes: "Finishing that 5K was the hardest thing I ever had to do.  I ate more fettuccine Alfredo, and drank less water than I have in my entire life.  People always talk about triumphs of the human spirit.  Today I had a triumph of the human body. My guts.  My heart. While I eventually puked my guts out, I never puked my heart out. And I am very, very proud of that.")
Workout.create(distance: 7.24, workout_date: "2017-03-24", runner_id: 17, notes: "Fitness if like the blade of a knife; you want to sharpen it without ruining the blade.")
Workout.create(distance: 4.99, workout_date: "2017-03-26", runner_id: 14, notes: "Flatter me, and I may not believe you.  Criticize me, and I may not like you.  Ignore me, and I may not forgive you.  Encourage me, and I will not forget you.  ")
Workout.create(distance: 2.49, workout_date: "2017-03-09", runner_id: 13, notes: "Get out there and do what you love!")
Workout.create(distance: 16.03, workout_date: "2017-03-01", runner_id: 3, notes: "Good judgment is the result of experience, experience is the result of bad judgment.")
Workout.create(distance: 12.2, workout_date: "2017-03-10", runner_id: 13, notes: "")
Workout.create(distance: 7.54, workout_date: "2017-03-16", runner_id: 18, notes: "Happiness is not a state to arrive at, but a manner of traveling.")
Workout.create(distance: 19.7, workout_date: "2017-02-01", runner_id: 5, notes: "Hard work beats talent when talent doesn't work hard.")
Workout.create(distance: 3.82, workout_date: "2017-01-05", runner_id: 13, notes: "I can make a difference. Remember I'm the one who started this whole thing off by hitting Meredith with my car. And I owe it to her to finish the G.D. 5K.")
Workout.create(distance: 6.25, workout_date: "2017-02-03", runner_id: 2, notes: "I eat whatever the guy who beat me in the last race ate.")
Workout.create(distance: 7.33, workout_date: "2017-01-26", runner_id: 7, notes: "")
Workout.create(distance: 14.42, workout_date: "2017-02-07", runner_id: 14, notes: "I ran to be free; I ran to avoid pain; I ran to feel pain; I ran out of love and hate and anger and joy.")
Workout.create(distance: 6.6, workout_date: "2017-02-26", runner_id: 3, notes: "I run because I used to be envious of people that could run, and now I am that person.")
Workout.create(distance: 12.06, workout_date: "2017-02-23", runner_id: 4, notes: "I run because it's my passion, and not just a sport.  Every time I walk out the door, I know why I'm going where I'm going and I'm already focused on that special place where I find my peace and solitude.  Running, to me, is more than just a physical exercise... it's a consistent reward for victory!")
Workout.create(distance: 7.12, workout_date: "2017-02-01", runner_id: 19, notes: "I tell my athletes, 'When you compete, concentrate on yourself. Don't focus on anger against a competitor.' ")
Workout.create(distance: 4.23, workout_date: "2017-01-19", runner_id: 15, notes: "I think some of the most celebrated moments in human achievement should be those times when everything is going against a person and they are down in the dumps but they simply choose to get up. That's real greatness!")
Workout.create(distance: 15.62, workout_date: "2017-02-11", runner_id: 18, notes: "I think there's only one sensible place for a person to be at 5:30 in the morning.  That's in bed.  And what am I doing?  I'm out running.  And I completely hate this.")
Workout.create(distance: 17.08, workout_date: "2017-01-11", runner_id: 8, notes: "I think we dream so we don't have to be apart so long.  If we're in each other's dreams, we can be together all the time.")
Workout.create(distance: 17.97, workout_date: "2017-02-08", runner_id: 6, notes: "I was born to run.  I love to run.  It's almost like the faster I go, the easier it becomes.")
Workout.create(distance: 1, workout_date: "2017-02-20", runner_id: 9, notes: "I'd rather run a gutsy race, pushing all the way and lose, than run a conservative race only for a win. ")
Workout.create(distance: 16.7, workout_date: "2017-02-16", runner_id: 6, notes: "I've always taken the philosophy that you have to dream a little in this sport. If you stay in your comfort zone, you're not going to do anything special.")
Workout.create(distance: 19.83, workout_date: "2017-02-22", runner_id: 6, notes: "If I accept you as you are, I will make you worse; however if I treat you as though you are what you are capable of becoming, I will help you become that.")
Workout.create(distance: 6.54, workout_date: "2017-02-14", runner_id: 19, notes: "If one can stick to the training throughout the many long years, then will power is no longer a problem.  It's raining?  That doesn't matter.  I am tired?  That's beside the point.  It's simply that I just have to.")
Workout.create(distance: 11.77, workout_date: "2017-02-20", runner_id: 11, notes: "If the furnace is hot enough it will burn anything.")
Workout.create(distance: 19.04, workout_date: "2017-02-22", runner_id: 8, notes: "")
Workout.create(distance: 8.18, workout_date: "2017-02-15", runner_id: 7, notes: "If what you did yesterday still looks big to you, you haven't done much today.")
Workout.create(distance: 4.2, workout_date: "2017-01-29", runner_id: 12, notes: "If you always do what you have always done, you will always get what you have received.")
Workout.create(distance: 10.22, workout_date: "2017-02-06", runner_id: 10, notes: "If you ask me how I want to be remembered, it is as a winner...")
Workout.create(distance: 11.96, workout_date: "2017-02-28", runner_id: 18, notes: "")
Workout.create(distance: 7.13, workout_date: "2017-01-31", runner_id: 15, notes: "If you don't have confidence, you'll always find a way not to win.")
Workout.create(distance: 16.67, workout_date: "2017-01-04", runner_id: 20, notes: "If you don't risk anything, you risk even more.")
Workout.create(distance: 16.05, workout_date: "2017-01-28", runner_id: 4, notes: "If you have a bad run, don't obsess about it.  You're always going to have days when your legs feel dead.")
Workout.create(distance: 10.6, workout_date: "2017-01-07", runner_id: 15, notes: "If you set your aim too high and don't fulfill it, then your enthusiasm turns to bitterness. Try for a goal that's reasonable, and then gradually raise it. ")
Workout.create(distance: 7.95, workout_date: "2017-01-05", runner_id: 5, notes: "")
Workout.create(distance: 10.63, workout_date: "2017-01-16", runner_id: 20, notes: "If you want to achieve a high goal, you're going to have to take some chances.")
Workout.create(distance: 11.24, workout_date: "2017-02-13", runner_id: 13, notes: "If you want to become the best runner you can be, start now.  Don't spend the rest of your life wondering if you can do it.")
Workout.create(distance: 13.07, workout_date: "2017-02-27", runner_id: 1, notes: "If you want to win a race you have to go a little berserk.")
Workout.create(distance: 19.82, workout_date: "2017-01-04", runner_id: 7, notes: "In order to succeed, we must first believe we can.")
Workout.create(distance: 11.37, workout_date: "2017-02-16", runner_id: 12, notes: "In running, it doesn't matter whether you come in first, in the middle of the pack, or last.  You can say, 'I have finished.'  There is a lot of satisfaction in that.")
Workout.create(distance: 17.34, workout_date: "2017-01-08", runner_id: 19, notes: "Independence is the outstanding characteristic of the runner.")
Workout.create(distance: 17.93, workout_date: "2017-02-21", runner_id: 19, notes: "It hurts up to a point and then it doesn't get any worse.")
Workout.create(distance: 16.94, workout_date: "2017-01-04", runner_id: 13, notes: "It is true that speed kills.  In distance running, it kills anyone who does not have it.")
Workout.create(distance: 18.44, workout_date: "2017-01-01", runner_id: 4, notes: "It takes education to be successful in the game of life.")
Workout.create(distance: 5.44, workout_date: "2017-01-03", runner_id: 17, notes: "It's my own space, my own time, when I'm just out there letting my thoughts go.  It's part of my day like eating, and it's one of my favorite parts.")
Workout.create(distance: 16.06, workout_date: "2017-02-28", runner_id: 15, notes: "It's not about speed and gold medals. It's about refusing to be stopped. ")
Workout.create(distance: 7.53, workout_date: "2017-02-20", runner_id: 4, notes: "It's very hard in the beginning to understand that the whole idea is not to beat the other runners.  Eventually you learn that the competition is against the little voice inside you that wants to quit.")
Workout.create(distance: 19.16, workout_date: "2017-02-27", runner_id: 13, notes: "It's what you learn after you know it all that counts.")
Workout.create(distance: 11.6, workout_date: "2017-02-04", runner_id: 4, notes: "")
Workout.create(distance: 19.98, workout_date: "2017-01-11", runner_id: 13, notes: "")
Workout.create(distance: 8.49, workout_date: "2017-02-05", runner_id: 16, notes: "The measure of who we are is what we do with what we have.")
Workout.create(distance: 17.81, workout_date: "2017-01-24", runner_id: 13, notes: "Jogging is very beneficial.  It's good for your legs and your feet.  It's also very good for the ground.  It makes it feel needed.")
Workout.create(distance: 3.93, workout_date: "2017-01-30", runner_id: 5, notes: "Joy lies in the fight, in the attempt, in the suffering involved, not in the victory itself.")
Workout.create(distance: 19.33, workout_date: "2017-01-21", runner_id: 11, notes: "Just do the best with what you have, and you'll soon be doing it better.")
Workout.create(distance: 6.89, workout_date: "2017-02-26", runner_id: 12, notes: "Keep away from people who try to belittle your ambitions.  Small people always do that, but the really great make you feel that you, too, can become great.")
Workout.create(distance: 9.31, workout_date: "2017-01-02", runner_id: 13, notes: "Keep your dream in front of you. Never let it go regardless of how farfetched it might seem. ")
Workout.create(distance: 16.12, workout_date: "2017-01-09", runner_id: 10, notes: "Keep your dreams alive.  Understand to achieve anything requires faith and belief in yourself, vision, hardwork, determination, and dedication.  Remember all things are possible for those who believe.")
Workout.create(distance: 14.16, workout_date: "2017-01-04", runner_id: 17, notes: "Learn to run when feeling the pain, then push harder.")
Workout.create(distance: 16.47, workout_date: "2017-02-07", runner_id: 18, notes: "Life (and running) is not all about time but about our experiences along the way.")
Workout.create(distance: 7.87, workout_date: "2017-01-10", runner_id: 16, notes: "Life is complicated. Running is simple.  Is it any wonder that people like to run?")
Workout.create(distance: 13.05, workout_date: "2017-01-18", runner_id: 2, notes: "Life is like topography, Hobbes. There are summits of happiness and success, flat stretches of boring routine, and valleys of frustration and failure.")
Workout.create(distance: 13.82, workout_date: "2017-01-10", runner_id: 2, notes: "Life is short... running makes it seem longer.")
Workout.create(distance: 16.7, workout_date: "2017-01-31", runner_id: 7, notes: "Life is thickly sown with thorns, and I know no other remedy than to pass quickly through them.  The longer we dwell on our misfortunes, the greater is their power to harm us.")
Workout.create(distance: 7.11, workout_date: "2017-02-19", runner_id: 10, notes: "Listen to your body. Do not be a blind and deaf tenant.")
Workout.create(distance: 10.94, workout_date: "2017-01-03", runner_id: 6, notes: "Many of life's failures are people who did not realize how close they were to success when they gave up.")
Workout.create(distance: 11.48, workout_date: "2017-01-03", runner_id: 17, notes: "Men are born to succeed, not fail.")
Workout.create(distance: 14.06, workout_date: "2017-01-09", runner_id: 11, notes: "Methinks that the moment my legs began to move, my thoughts began to flow.")
Workout.create(distance: 2.1, workout_date: "2017-02-07", runner_id: 1, notes: "Michael, 5K means five kilometers, not five thousand miles...")
Workout.create(distance: 11.26, workout_date: "2017-01-06", runner_id: 2, notes: "Most people are like a falling leaf that drifts and turns in the air, flutters, and falls to the ground.  But a few others are like stars which travel one defined path: no wind reaches them, they have within themselves their guide and path.")
Workout.create(distance: 5.63, workout_date: "2017-01-08", runner_id: 15, notes: "Motivation is a skill. It can be learned and practiced. ")
Workout.create(distance: 8.96, workout_date: "2017-01-15", runner_id: 3, notes: "My outlook is that I never want to look back and wonder how fast I could have been.")
Workout.create(distance: 11.82, workout_date: "2017-02-28", runner_id: 19, notes: "My whole feeling in terms of racing is that you have to be very bold. You sometimes have to be aggressive and gamble. ")
Workout.create(distance: 2.9, workout_date: "2017-01-27", runner_id: 19, notes: "Never give up.")
Workout.create(distance: 18.13, workout_date: "2017-02-22", runner_id: 6, notes: "Never surrender opportunity to security.")
Workout.create(distance: 2.85, workout_date: "2017-02-06", runner_id: 17, notes: "Ninety-eight percent of success is in the head and the heart.")
Workout.create(distance: 16.46, workout_date: "2017-02-12", runner_id: 12, notes: "")
Workout.create(distance: 7.57, workout_date: "2017-01-13", runner_id: 7, notes: "No negative thoughts cross my mind on race day. When I look into their eyes, I know I'm going to beat them.")
Workout.create(distance: 13.36, workout_date: "2017-01-10", runner_id: 7, notes: "Nothing splendid has ever been achieved except by those who dared believe that something inside of them was superior to circumstance.")
Workout.create(distance: 10.76, workout_date: "2017-01-12", runner_id: 17, notes: "Nothing's better than the wind to your back, the sun in front of you, and your friends beside you.")
Workout.create(distance: 16.47, workout_date: "2017-01-24", runner_id: 2, notes: "Number one is to just gain a passion for running.  To love the morning, to love the trail, to love the pace on the track.  And if some kid gets really good at it, that's cool too.")
Workout.create(distance: 7.96, workout_date: "2017-02-18", runner_id: 14, notes: "Obstacles are those frightening things that become visible when we take our eyes off our goals.")
Workout.create(distance: 7, workout_date: "2017-02-04", runner_id: 15, notes: "Oh yes, I will work out today. I will work out a way to avoid running for a stupid cause.")
Workout.create(distance: 2.46, workout_date: "2017-02-16", runner_id: 3, notes: "")
Workout.create(distance: 5.72, workout_date: "2017-01-19", runner_id: 15, notes: "One thing about racing is that it hurts. You better accept that from the beginning or you're not going anywhere. ")
Workout.create(distance: 14.9, workout_date: "2017-02-14", runner_id: 19, notes: "Only those who will risk going to far can possibly find out how far they can go.")
Workout.create(distance: 16.64, workout_date: "2017-02-27", runner_id: 18, notes: "")
Workout.create(distance: 16.98, workout_date: "2017-01-27", runner_id: 15, notes: "Out on the roads there is fitness and self-discovery and the persons we were destined to be.")
Workout.create(distance: 15.46, workout_date: "2017-02-01", runner_id: 11, notes: "Passion is pushing myself when there is no one else around- just me and the road.")
Workout.create(distance: 4.48, workout_date: "2016-06-07", runner_id: 6, notes: "Racing is pain, and that's why you do it, to challenge yourself and the limits of your physical and mental barriers. You don't experience that in an armchair watching television. ")
Workout.create(distance: 18.09, workout_date: "2015-02-12", runner_id: 8, notes: "Racing teaches us to challenge ourselves.  It teaches us to push beyond where we thought we could go.  It helps us to find out what we are made of.  This is what we do.  This is what it's all about.")
Workout.create(distance: 5.08, workout_date: "2016-12-21", runner_id: 14, notes: "Reality can destroy the dream; why shouldn't the dream destroy reality?")
Workout.create(distance: 16.39, workout_date: "2015-04-21", runner_id: 3, notes: "Recognize your victories. ")
Workout.create(distance: 9.89, workout_date: "2015-11-19", runner_id: 13, notes: "Remember, the feeling you get from a good run is far better than the feeling you get from sitting around wishing you were running. ")
Workout.create(distance: 16.15, workout_date: "2015-02-08", runner_id: 1, notes: "Run hard, be strong, think big!")
Workout.create(distance: 15.94, workout_date: "2015-08-18", runner_id: 1, notes: "Running changed my life as it will change yours, just give it a chance. Once you get that blood moving, it's show time!")
Workout.create(distance: 14.17, workout_date: "2015-03-11", runner_id: 7, notes: "Running gives me confidence.")
Workout.create(distance: 9.08, workout_date: "2015-03-06", runner_id: 16, notes: "Running is 80 percent mental.")
Workout.create(distance: 5.47, workout_date: "2015-11-01", runner_id: 16, notes: "")
Workout.create(distance: 1.83, workout_date: "2016-09-20", runner_id: 16, notes: "Running is my sunshine.")
Workout.create(distance: 13.49, workout_date: "2015-07-29", runner_id: 18, notes: "Running is one of the best solution to a clear mind.")
Workout.create(distance: 2.77, workout_date: "2015-05-05", runner_id: 5, notes: "Running is ultimately a personal experience.  It is a revival of the spirit, a private oasis for the thirsty mind.  Yet, its healing power only increases in the presence of others.  Run together and the oasis grows cooler and more satisfying.")
Workout.create(distance: 17.78, workout_date: "2016-01-01", runner_id: 15, notes: "Running makes my life whole.")
Workout.create(distance: 9.33, workout_date: "2016-03-24", runner_id: 6, notes: "Running well is a matter of having the patience to persevere when we are tired and not expecting instant results. ")
Workout.create(distance: 11.87, workout_date: "2016-07-14", runner_id: 6, notes: "")
Workout.create(distance: 16.36, workout_date: "2016-06-07", runner_id: 14, notes: "Self-trust is the essence of heroism.")
Workout.create(distance: 15.84, workout_date: "2015-08-28", runner_id: 4, notes: "Some days even my lucky rocket ship underpants won't help.")
Workout.create(distance: 13.46, workout_date: "2016-12-12", runner_id: 20, notes: "Some runners judge performance by whether they won or lost. Others define success or failure by how fast they ran. Only you can judge your performance. Avoid letting others sit in judgment of you.")
Workout.create(distance: 4.24, workout_date: "2016-04-23", runner_id: 12, notes: "")
Workout.create(distance: 11.33, workout_date: "2016-01-30", runner_id: 17, notes: "Spirit...has fifty times the strength and staying power of brawn and muscle.")
Workout.create(distance: 15.91, workout_date: "2015-02-13", runner_id: 9, notes: "Success does not come to the most righteous and rigorously disciplined but to those who continue running.")
Workout.create(distance: 10.98, workout_date: "2016-02-25", runner_id: 17, notes: "")
Workout.create(distance: 15.29, workout_date: "2015-11-01", runner_id: 19, notes: "Success is a state of mind.  If you want success, start thinking of yourself as a success.")
Workout.create(distance: 2.18, workout_date: "2015-11-29", runner_id: 15, notes: "The battles that count aren't the ones for gold medals. The struggles within yourself - the invisible, inevitable battles inside all of us - that's where it's at.")
Workout.create(distance: 12.83, workout_date: "2016-04-24", runner_id: 10, notes: "The biggest mistake an athlete can make is to be afraid of making one.")
Workout.create(distance: 11.22, workout_date: "2015-10-12", runner_id: 17, notes: "The crime is not to avoid failure, the crime is to not give triumph a chance.")
Workout.create(distance: 10.71, workout_date: "2016-04-03", runner_id: 7, notes: "The desire to run comes from deep within us- from the unconscious, the instinctive, the intuitive.")
Workout.create(distance: 15.68, workout_date: "2015-10-15", runner_id: 18, notes: "The essential thing in life is not so much conquering as fighting as well.")
Workout.create(distance: 12.56, workout_date: "2015-10-16", runner_id: 12, notes: "The freedom of cross country is so primitive.  It's woman vs. nature.")
Workout.create(distance: 6.41, workout_date: "2016-06-03", runner_id: 16, notes: "")
Workout.create(distance: 5.09, workout_date: "2016-10-30", runner_id: 15, notes: "The greatest barrier to success is the fear of failure.")
Workout.create(distance: 3.97, workout_date: "2016-04-26", runner_id: 10, notes: "The greatest danger to most of us lies not in setting our aim too high and falling short, but in setting our aim too low, and achieving our mark.")
Workout.create(distance: 15.91, workout_date: "2015-02-09", runner_id: 5, notes: "The important thing is the attitude of the athlete, the desire to get to the top.")
Workout.create(distance: 5.31, workout_date: "2016-04-03", runner_id: 8, notes: "The impossible is often the untried.")
Workout.create(distance: 10.87, workout_date: "2015-11-20", runner_id: 15, notes: "The man who can drive himself further once the effort gets painful is the man who will win.")
Workout.create(distance: 6.47, workout_date: "2016-12-20", runner_id: 12, notes: "The more I train, the more I realize I have more speed in me.")
Workout.create(distance: 13.26, workout_date: "2015-09-06", runner_id: 6, notes: "The most beautiful motion is that which accomplishes the greatest results with the least amount of effort.")
Workout.create(distance: 16.39, workout_date: "2015-06-10", runner_id: 9, notes: "The most important day in any running program is rest.  Rest days give your muscles time to recover so you can run again.  Your muscles build in strength as you rest.")
Workout.create(distance: 10.15, workout_date: "2015-04-12", runner_id: 13, notes: "The most important message I stress to beginners is to learn to love the sport.  Like other endeavors, if running is not undertaken properly, it can be difficult and discouraging.")
Workout.create(distance: 2.39, workout_date: "2015-02-24", runner_id: 16, notes: "")
Workout.create(distance: 19.7, workout_date: "2016-06-28", runner_id: 10, notes: "The only place that success comes before work is in the dictionary.")
Workout.create(distance: 13.59, workout_date: "2015-12-30", runner_id: 15, notes: "The only way of finding the limits of the possible is by going beyond them into the impossible.")
Workout.create(distance: 5.04, workout_date: "2015-11-21", runner_id: 4, notes: "The race does not always go to the swift, but to the ones who keep running.")
Workout.create(distance: 1.2, workout_date: "2015-03-15", runner_id: 8, notes: "The secret of getting ahead is getting started. The secret of getting started is breaking your complex overwhelming tasks into small manageable tasks, and then starting on the first one.")
Workout.create(distance: 15.02, workout_date: "2015-05-22", runner_id: 8, notes: "")
Workout.create(distance: 4.81, workout_date: "2015-07-11", runner_id: 5, notes: "The trouble with jogging is that by the time you realize you're not in shape for it, it's too far to walk back.")
Workout.create(distance: 4.22, workout_date: "2016-10-02", runner_id: 4, notes: "The will to win means nothing if you haven't the will to prepare.")
Workout.create(distance: 12.06, workout_date: "2016-12-07", runner_id: 14, notes: "")
Workout.create(distance: 8.64, workout_date: "2015-06-11", runner_id: 3, notes: "The woods are lovely dark and deep, but I have promises to keep, and miles to go before I sleep, and miles to go before I sleep.")
Workout.create(distance: 8.63, workout_date: "2015-04-16", runner_id: 12, notes: "")
Workout.create(distance: 10.94, workout_date: "2016-12-28", runner_id: 16, notes: "There's no such thing as bad weather, just soft people.")
Workout.create(distance: 10.42, workout_date: "2015-12-30", runner_id: 17, notes: "There's nothing a man can't do if the spirit's there.")
Workout.create(distance: 18.78, workout_date: "2015-10-28", runner_id: 14, notes: "")
Workout.create(distance: 9.28, workout_date: "2016-10-09", runner_id: 19, notes: "They say the breaks even up in the long run, and the trick is to be a long-distance runner.")
Workout.create(distance: 1.83, workout_date: "2016-09-06", runner_id: 3, notes: "This describes the pure essence of why we run.  Spoken about Roger Bannister, the first man to break the 4-minute mile.")
Workout.create(distance: 19.5, workout_date: "2015-01-30", runner_id: 17, notes: "This is not about instant gratification. You have to work hard for it, sweat for it, give up sleeping in on Sunday mornings. ")
Workout.create(distance: 5.86, workout_date: "2015-05-15", runner_id: 16, notes: "This is what really matters: running. This is where I know where I am. ")
Workout.create(distance: 2.29, workout_date: "2016-03-24", runner_id: 10, notes: "")
Workout.create(distance: 12.19, workout_date: "2016-01-24", runner_id: 5, notes: "To give anything less than your best is the sacrifice the gift.")
Workout.create(distance: 8.15, workout_date: "2015-07-16", runner_id: 16, notes: "To keep from decaying, to be a winner, the athlete must accept pain - not only accept it, but look for it, live with it, learn not to fear it.")
Workout.create(distance: 10.88, workout_date: "2015-02-28", runner_id: 19, notes: "To make your life a work of art, you must have the material to work with. The race, any race, is just such an experience. ")
Workout.create(distance: 4.26, workout_date: "2015-12-02", runner_id: 7, notes: "Tough times don't last but tough people do.")
Workout.create(distance: 8.26, workout_date: "2015-11-06", runner_id: 13, notes: "We all have dreams.  In order to make dreams come into reality, it takes an awful lot of determination, dedication, self-discipline and effort.")
Workout.create(distance: 15.97, workout_date: "2015-03-26", runner_id: 14, notes: "")
Workout.create(distance: 5.52, workout_date: "2016-04-30", runner_id: 10, notes: "We are what we repeatedly do.  Excellence, then, is not an act, but a habit.")
Workout.create(distance: 11.76, workout_date: "2015-09-16", runner_id: 2, notes: "We can't all be heroes because someone has to sit on the curb and clap as they go by.")
Workout.create(distance: 7.62, workout_date: "2015-01-08", runner_id: 16, notes: "We may train or peak for a certain race, but running is a lifetime sport.")
Workout.create(distance: 4.66, workout_date: "2015-06-12", runner_id: 6, notes: "")
Workout.create(distance: 2.9, workout_date: "2015-10-30", runner_id: 15, notes: "What fun is it being cool if you can't wear a sombrero?")
Workout.create(distance: 3.46, workout_date: "2016-02-20", runner_id: 2, notes: "")
